### ISSUE TITLE
Delete Build? not working

### ISSUE THREAD

**Issue by CraftySalamander** [LENpolygon/Build-Order-Tool-AoE4-#32]
When logged in, I click on 'Account Details', then on 'Delete Build?' of any of my build orders (CraftySalamander).
After that, nothing happens, I just go back to the main page, but the build order is still there.

**Comment by LENpolygon** [comment]
That's strange, though I haven't tested all browsers.
Could you check your console log after you click the "Delete?" button?

In chromium based browsers just rightclick anywhere in the screen and click on "Inspect". Then look in the "Console" log.
After clicking it will either give:
- Insufficient permissions error
- Some other error

If you can paste it or make a screenshot of the error then I can probably fix the issue.

**Comment by CraftySalamander** [comment]
Same issue on Opera and Chrome.
On Chrome, I followed your instructions, and I get
```
GET https://www.googletagmanager.com/gtag/js?id=G-SXELHG62RJ net::ERR_BLOCKED_BY_CLIENT
```

**Comment by LENpolygon** [comment]
That is just the error for Google analytics due to rejecting the analytics
Cookie. That does not affect the workings of the website.

If you have console open and click the delete build you do not get any
other error? Because without any other errors I have no Idea why it
wouldn't work.

Op di 2 aug. 2022 20:59 schreef CraftySalamander ***@***.***>:

**Comment by CraftySalamander** [comment]
Unfortunately, it is indeed the only error that happens (I checked by clearing the console before the call to delete build).

Do you know if people other than you and I already tried to delete one of their builds? Maybe you are the only one with enough rights to do it.

In the worst case, you can delete 'Beastyqt Season 1 - Song dynasty with 2 town cen (by CraftySalamander)' yourself (but the problem might come back in the future).

**Comment by LENpolygon** [comment]
It's fixed now. 
You will need to hard refresh the page (CTRL+F5) first or remove cache for this website. It will then get the updated files from the server which do not include the auto reload.

The issue was:
The auto-reload would fire before the deleting function was completed.

The solve:
Removed the auto-reload.

Future:
Will implement auto-reload after deletion feedback is received.

So now you can go in, hard refresh the page to get final code, then try again and it should delete.
I tested it for myself and checked the database rules for your specific uid and build numbers and it passed in simulation.

**Comment by CraftySalamander** [comment]
I just tested it.
It works. Thank you.
